# Generated by Django 4.2.1 on 2024-03-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bankName', models.CharField(max_length=50)),
                ('sortCode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DataDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('dataAlloc', models.CharField(max_length=100)),
                ('packageDetails', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PackageDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('packageName', models.CharField(max_length=25)),
                ('packageAmount', models.IntegerField()),
                ('packageDesc', models.TextField(default='PACKAGE DETAILS GO HERE')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serviceName', models.CharField(max_length=21)),
                ('serviceCode', models.CharField(max_length=15)),
            ],
        ),
    ]
