# Generated by Django 4.2.1 on 2024-03-16 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataDetails',
        ),
    ]
